{% set version = "0.5.5" %}

package:
  name: pydantic-partial
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/p/pydantic-partial/pydantic_partial-{{ version }}.tar.gz
    sha256: a903bdf6b2b30c850865843645432537eae81713fba59ee03bae567eb4c4ff3b
  - folder: src
    url: https://github.com/team23/pydantic-partial/archive/refs/tags/v{{ version }}.tar.gz
    sha256: ff122e16bdd5205e25cec5480449c7a442685d47ea43614740e7eef75b4433c1

build:
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.9
  run:
    - pydantic >=1.9.0,<3.0.0
    - python >=3.9.0

test:
  source_files:
    - src/tests
  imports:
    - pydantic_partial
  commands:
    - pip check
    - coverage run --source=pydantic_partial --branch -m pytest -vv --color=yes --tb=long
    - coverage report --show-missing --skip-covered --fail-under=99
  requires:
    - coverage
    - pip
    - pytest

about:
  home: https://github.com/team23/pydantic-partial
  summary: Create partial models from your pydantic models. Partial models may allow None for certain or all fields.
  license: MIT
  license_file: dist/LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
