schema_version: 1

context:
  version: 0.7.0

package:
  name: pydantic-partial
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/p/pydantic-partial/pydantic_partial-${{ version }}.tar.gz
    sha256: c3006ef577bcb9670f277cdf0ac74735917494f637d3d1faa675d40c31ec018a
    target_directory: dist
  - url: https://github.com/team23/pydantic-partial/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 93f4db0508891aacd2eba53d153cb40efc6f9e35c999b4a3e132addf1e637575
    target_directory: src

build:
  number: 0
  noarch: python
  script:
    - cd dist
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python ${{ python_min }}.*
  run:
    - pydantic >=1.9.0,<3.0.0
    - python >=${{ python_min }}

tests:
  - python:
      pip_check: true
      python_version: ${{ python_min }}.*
      imports: pydantic_partial
  - files:
      source:
        - src/tests/
    requirements:
      run:
        - coverage
        - pytest
        - python ${{ python_min }}.*
    script:
      - coverage run --source=pydantic_partial --branch -m pytest -vv --color=yes --tb=long
      - coverage report --show-missing --skip-covered --fail-under=99

about:
  summary: Create partial models from your pydantic models. Partial models may allow None for certain or all fields.
  license: MIT
  license_file: dist/LICENSE
  homepage: https://github.com/team23/pydantic-partial

extra:
  recipe-maintainers:
    - bollwyvl
