schema_version: 1

context:
  version: "0.9.0"

package:
  name: pydantic-partial
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/p/pydantic-partial/pydantic_partial-${{ version }}.tar.gz
    sha256: c512c1888b17d377cdf3f3d56c76df8453b6dc68f942b4a0dba48427037c019c
    target_directory: dist
  - url: https://github.com/team23/pydantic-partial/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 8121ba9344022edc0ae2fa5634d38438140b0a4adc9365ed82791df365f26b63
    target_directory: src

build:
  number: 0
  noarch: python
  script:
    - cd dist
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python ${{ python_min }}.*
  run:
    - pydantic >=2.0.0,<3.0.0
    - python >=${{ python_min }}

tests:
  - python:
      imports: pydantic_partial
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
  - files:
      source:
        - src/tests/
    requirements:
      run:
        - coverage
        - fastapi
        - pytest
        - python ${{ python_min }}.*
    script:
      - coverage run --source=pydantic_partial --branch -m pytest -vv --color=yes --tb=long
      - coverage report --show-missing --skip-covered --fail-under=99

about:
  summary: Create partial models from your pydantic models. Partial models may allow None for certain or all fields.
  license: MIT
  license_file: dist/LICENSE
  homepage: https://github.com/team23/pydantic-partial

extra:
  recipe-maintainers:
    - bollwyvl
